#!/bin/bash

echo -e "fastestmirror=True\nmax_parallel_downloads=10" | sudo tee -a /etc/dnf/dnf.conf > /dev/null

sudo dnf install -y \
  https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm \
  https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm

sudo dnf group upgrade -y multimedia --setopt="install_weak_deps=False" --exclude=PackageKit-gstreamer-plugin
sudo dnf group upgrade -y sound-and-video

# sudo dnf install -y akmod-nvidia xorg-x11-drv-nvidia-cuda
#
# sudo fwupdmgr refresh --force
# sudo fwupdmgr update -y || true
#
# echo "Waiting for NVIDIA kernel module build to complete..."
# sudo akmods --force
