################### File: ~/.config/MangoHud/MangoHud.conf ###################

# --- PERFORMANCE LIMITS ---
# FPS limits
fps_limit=30,40,50,60,75
# Force VSync OFF to ensure the 60 FPS limit works on a 75Hz screen
# vsync=0
# gl_vsync=0

# --- VISUAL STYLING ---
legacy_layout=false
position=top-left
hud_compact=false
round_corners=10
background_alpha=0.5
font_size=18
width=250

# --- GPU SENSORS ---
gpu_stats
gpu_temp
gpu_power
gpu_core_clock
gpu_mem_clock
# Shows a graph of GPU usage history
gpu_load_change
gpu_color=2E9762

# --- CPU SENSORS ---
cpu_stats
cpu_temp
cpu_power
cpu_mhz
# Shows a graph of CPU usage history
cpu_load_change
cpu_color=2E97CB

# --- MEMORY ---
vram
ram
ram_color=C26693

# --- FRAMERATE & FRAMETIMES ---
fps
frametime
# Shows the frame pacing graph (crucial for detecting micro-stutters)
frame_timing
# Toggle the overlay visibility on/off
toggle_hud=Shift_R+F12

# --- SHORTCUTS ---
# Right Shift + Home: Toggle the overlay visibility on/off
toggle_hud=Shift_R+Home
# Right Shift + End: Cycle between different FPS limits (60 -> 75 -> 0/Uncapped)
toggle_fps_limit=Shift_R+End
# Right Shift + Page Up: Move the overlay to different corners
toggle_hud_position=Shift_R+Page_Down

# --- CUSTOM ---
custom_text=CONFIG LOADED!
